### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by bilAlid** [elirabalison/API_Gestion_Materiel_Symfony#1]
Bonjour @elirabalison 
Thank you for your good work!
I have two requests:
1. Can you find a way to reduce the size of controller. We use the policy of "Thin controller" here at ManaTime
2. Can you fix the route path, it seems that it doesn't work well

**Comment by elirabalison** [comment]
Bonjour @bilAlid, 
Thank you for your feedback and kind words! 
I have implemented the changes based on your requests:
- Reduced Controller Size: Following the 'Thin controller' policy, I have refactored the controller by extracting the business logic into a separate service. This approach adheres to best practices, ensuring a clean and organized code structure while promoting reusability and maintainability.
- Fixed Route Path: I have investigated the issue with the route path and made the necessary corrections to ensure it now functions correctly.
Please feel free to test these changes and let me know if everything is working as expected. If you have any more feedback or if there's anything else I can assist you with, please don't hesitate to reach out.

**Comment by bilAlid** [comment]
Merci @elirabalison !
Je valide le passage pour l'étape suivante 👍
